allowBuilds:
  esbuild: set this to true or false
  protobufjs: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@3.0.148'
  - ai@6.0.224
